// <auto-generated />
using System;
using BusOverview.Repository.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BusOverview.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20181028232804_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("BusOverview.Model.Linha", b =>
                {
                    b.Property<int>("LinhaId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NomeLinha");

                    b.Property<int>("NumBuracos");

                    b.Property<int>("NumLomnbadas");

                    b.Property<int>("NumParadas");

                    b.Property<int>("NumSemnaforo");

                    b.Property<double>("Peso");

                    b.HasKey("LinhaId");

                    b.ToTable("Linha");
                });

            modelBuilder.Entity("BusOverview.Model.LinhaDetalhe", b =>
                {
                    b.Property<int>("LinhaDetalheId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateHora");

                    b.Property<double>("Latitude");

                    b.Property<int>("LinhaId");

                    b.Property<double>("Longitude");

                    b.HasKey("LinhaDetalheId");

                    b.ToTable("LinhasDetalhe");
                });

            modelBuilder.Entity("BusOverview.Repository.Entities.Model.DetecaoTipo", b =>
                {
                    b.Property<int>("DetecaoTipoId")
                        .ValueGeneratedOnAdd();

                    b.HasKey("DetecaoTipoId");

                    b.ToTable("DetecaoTipo");
                });

            modelBuilder.Entity("BusOverview.Repository.Entities.Model.OcorrenciaTipo", b =>
                {
                    b.Property<int>("OcorrenciaTipoId")
                        .ValueGeneratedOnAdd();

                    b.HasKey("OcorrenciaTipoId");

                    b.ToTable("OcorrenciaTipo");
                });

            modelBuilder.Entity("BusOverview.Repository.Entities.Model.SeveridadeTipo", b =>
                {
                    b.Property<int>("SeveridadeTipoId")
                        .ValueGeneratedOnAdd();

                    b.HasKey("SeveridadeTipoId");

                    b.ToTable("SeveridadeTipo");
                });
#pragma warning restore 612, 618
        }
    }
}
